<?php

namespace AppBundle\Repository;

/**
 * AnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswersRepository extends \Doctrine\ORM\EntityRepository
{
    
//      public function checkTheAnswer( $answers){
//        $em = $this->getEntityManager();
//        $query = $em->createQuery(
//                'SELECT u FROM AppBundle:Answers u'
//                . ' WHERE u.id = :answerId'
//                )->setParameter('answerid', $answers);
//        $answerCorrectness = $query->getResult();
//        return $answerCorrectness;
//    }
}
