<?php

namespace AppBundle\Repository;

/**
 * EnvelopesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvelopesRepository extends \Doctrine\ORM\EntityRepository
{
}
