<?php

namespace AppBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findFinishedGamesByUser($user) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'SELECT u FROM AppBundle:game u'
                . ' WHERE u.users = :userId AND u.isFinished = 1'
                )->setParameter('userId', $user);
        $gamesFinshedByUser = $query->getResult();
        return $gamesFinshedByUser;
    }
    
    
}
